using System;
using System.Collections.Generic;
namespace MusicHax
{
    public static class FileStructure
    {
        public static readonly string[] SFX =
        {
            "announcer_candyman",
            "announcer_dice",
            "announcer_doombox",
            "announcer_dustandashes",
            "announcer_eight",
            "announcer_five",
            "announcer_four",
            "announcer_game",
            "announcer_get_ready",
            "announcer_grid",
            "announcer_jet",
            "announcer_latch",
            "announcer_lethal_league",
            "announcer_nine",
            "announcer_nitro",
            "announcer_one",
            "announcer_play_ball",
            "announcer_random",
            "announcer_raptor",
            "announcer_select",
            "announcer_seven",
            "announcer_six",
            "announcer_sonata",
            "announcer_switch",
            "announcer_ten",
            "announcer_three",
            "announcer_time_up",
            "announcer_toxic",
            "announcer_two",
            "bubble_pop",
            "catch",
            "deflect",
            "express",
            "get_hit1",
            "get_hit2",
            "get_hit3",
            "get_hit4",
            "getupgrab",
            "graffitiPlace",
            "jump",
            "kill",
            "KO_in",
            "KO_out",
            "lobby_character_select",
            "lobby_player_in",
            "lobby_player_out",
            "lobby_start_game",
            "medium_hit",
            "medium_smash",
            "menu_back",
            "menu_confirm",
            "menu_scroll",
            "menu_set",
            "next_line",
            "page_turn",
            "parry",
            "parry_activate",
            "parry_counter",
            "powerup_heal",
            "powerup_insert",
            "powerup_insert_noroll",
            "powerup_invisible",
            "powerup_multi_bounce",
            "powerup_phantom_hit",
            "powerup_random",
            "powerup_result",
            "powerup_spark",
            "powerup_ultra",
            "powerup_warp",
            "result_xp_gain",
            "sax1",
            "sax10",
            "sax11",
            "sax2",
            "sax3",
            "sax4",
            "sax5",
            "sax6",
            "sax7",
            "sax8",
            "sax9",
            "special_activate",
            "strong_hit",
            "strong_smash",
            "swing",
            "teleport",
            "throw",
            "tutorial_ok",
            "volleyball_hit",
            "volleyball_smash",
            "wall_bounce",
            "wall_bounce_fast",
            "weak_hit",
            "weak_smash",
        };

        public static readonly string[] Songs =
        {
            "AAron EVO - Beverly Chills",
            "B. Bravo & Lean Rock - Shred",
            "Bignic - Ruiner",
            "Bignic - Scream",
            "D Fast - Jungaaaa",
            "D Fast - Whipz",
            "Doctor Lazer - Headbangeren",
            "Doctor Lazer - Thuggin",
            "Frank Klepacki - Decible",
            "Grillo - Urabon",
            "Hideki Naganuma - AIN'T NOTHIN' LIKE A FUNKY BEAT",
            "Klaus Veen - Dial Hop",
            "Klaus Veen - Ordinary Days",
            "Klaus Veen - Ordinary Days V2",
            "Klaus Veen - Snibbit",
            "Pixelord - Dominator",
            "Pixelord - Killa Swing",
            "The Sleepers RecordZ ft. Nasty Den - Nasty Lovers",
            "zeroSCAR - X",
        };

        public static readonly string[] Voices =
        {
            "_gamewin",
            "_gethit",
            "_intense_swing",
            "_jump",
            "_normal_swing",
            "_score",
            "_special_activation",
        };
    }
}
